import type { GraphEdge, GraphNode, ScenarioDefinition } from '@vsm/shared';

// Authoring fixture only. Importing this module never writes to PostgreSQL.
// Stable IDs allow manual import/review and deterministic tests.
const uuid = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const scenarioId = uuid(27);
const sit = (n: number, title: string, text: string, x: number): GraphNode => ({
  id: uuid(n),
  type: 'situation',
  title,
  text,
  position: { x, y: 180 },
  timerSeconds: 60,
  finishOnTimeout: false,
  timeoutEffects: { loyalty: -8, safety: -4 },
  timeoutExplanation: 'Время ответа истекло: обращение осталось без своевременной помощи.',
});
const edge = (n: number, source: number, target: number, trigger?: 'timeout'): GraphEdge => ({
  id: uuid(n),
  source: uuid(source),
  target: uuid(target),
  ...(trigger ? { trigger } : {}),
});

const nodes: GraphNode[] = [
  sit(
    101,
    'Принять обращение',
    'Пассажир сообщает, что его место и столик загрязнены. Как ответить?',
    30,
  ),
  {
    id: uuid(102),
    type: 'answer',
    title: 'Признать неудобство',
    text: 'Извиниться, признать проблему и предложить проверить место.',
    position: { x: 330, y: 60 },
    effects: { loyalty: 8, safety: 1, competencies: { communication: 4, service: 2 } },
    explanation: 'Обращение принято уважительно; причина ещё требует осмотра.',
    improvement: 'Осмотрите место и уточните, что именно требуется убрать или заменить.',
  },
  {
    id: uuid(103),
    type: 'answer',
    title: 'Отказать',
    text: 'Сказать пассажиру, что он должен решить вопрос сам.',
    position: { x: 330, y: 350 },
    effects: { loyalty: -12, safety: -2, competencies: { communication: -4, service: -4 } },
    explanation: 'Жалоба отклонена, загрязнение осталось без проверки.',
    improvement: 'Признайте неудобство, осмотрите место и организуйте помощь.',
  },
  sit(104, 'Осмотреть место', 'Подойдите к месту и проверьте загрязнение.', 650),
  {
    id: uuid(105),
    type: 'worldAction',
    title: 'Осмотреть столик',
    text: 'Осмотреть место рядом с пассажиром.',
    command: 'inspect',
    targetId: 'seat',
    position: { x: 940, y: 180 },
    effects: { loyalty: 2, safety: 2, competencies: { service: 2 } },
    explanation: 'Осмотр подтверждает проблему перед запросом услуги.',
    improvement: 'После осмотра свяжитесь с обслуживающим персоналом.',
  },
  sit(
    106,
    'Запросить уборку',
    'Проблема подтверждена. Используйте служебную связь для запроса уборки.',
    1250,
  ),
  {
    id: uuid(107),
    type: 'worldAction',
    title: 'Направить запрос',
    text: 'Передать запрос на уборку. Это ещё не означает, что уборка выполнена.',
    command: 'request_service',
    targetId: 'radio',
    requires: [uuid(105)],
    position: { x: 1540, y: 180 },
    effects: { loyalty: 3, safety: 1, competencies: { service: 3 } },
    explanation: 'Услуга запрошена; её результат пока не подтверждён.',
    improvement: 'Вернитесь к месту и проверьте выполнение услуги.',
  },
  sit(
    108,
    'Проверить выполнение',
    'Вернитесь к месту и убедитесь, что уборка действительно выполнена.',
    1850,
  ),
  {
    id: uuid(109),
    type: 'worldAction',
    title: 'Подтвердить результат',
    text: 'Проверить результат уборки у места пассажира.',
    command: 'confirm_service',
    targetId: 'seat',
    requires: [uuid(107)],
    position: { x: 2140, y: 180 },
    effects: { loyalty: 5, safety: 2, competencies: { service: 4, safety: 1 } },
    explanation: 'После запроса отдельно проверен результат учебной услуги.',
    improvement: 'Уточните у пассажира, комфортно ли ему теперь.',
  },
  sit(
    110,
    'Получить обратную связь',
    'Спросите пассажира, решена ли проблема и комфортно ли ему.',
    2450,
  ),
  {
    id: uuid(111),
    type: 'worldAction',
    title: 'Уточнить комфорт',
    text: 'Получить обратную связь от пассажира.',
    command: 'follow_up',
    targetId: 'passenger',
    requires: [uuid(109)],
    position: { x: 2740, y: 180 },
    effects: { loyalty: 5, safety: 0, competencies: { communication: 3, service: 2 } },
    explanation: 'Проводник убедился, что пассажиру комфортно после подтверждённой уборки.',
    improvement: 'Сохраните спокойный и внимательный тон.',
  },
  {
    id: uuid(112),
    type: 'end',
    title: 'Проблема решена',
    text: 'Уборка запрошена, выполнение проверено, комфорт уточнён.',
    outcome: 'resolved',
    position: { x: 3050, y: 180 },
  },
  {
    id: uuid(113),
    type: 'end',
    title: 'Отказ',
    text: 'Обращение отклонено, проблема не решена.',
    outcome: 'refused',
    position: { x: 650, y: 400 },
  },
  {
    id: uuid(114),
    type: 'end',
    title: 'Истекло время',
    text: 'На активном шаге не выполнено действие в отведённое время.',
    outcome: 'timeout',
    position: { x: 3050, y: 450 },
  },
];

const edges: GraphEdge[] = [
  edge(201, 101, 102),
  edge(202, 101, 103),
  edge(203, 102, 104),
  edge(204, 103, 113),
  edge(205, 104, 105),
  edge(206, 105, 106),
  edge(207, 106, 107),
  edge(208, 107, 108),
  edge(209, 108, 109),
  edge(210, 109, 110),
  edge(211, 110, 111),
  edge(212, 111, 112),
  ...[101, 104, 106, 108, 110].map((source, index) => edge(220 + index, source, 114, 'timeout')),
];

export const immersiveSeedDefinitions: ScenarioDefinition[] = [
  {
    schemaVersion: 2,
    id: scenarioId,
    kind: 'scenario',
    title: 'Грязное место',
    description:
      'Пассажир обнаружил грязное место. Осмотрите его, организуйте уборку и проверьте, что пассажиру снова комфортно.',
    serviceClass: 'comfort',
    difficulty: 'beginner',
    estimatedMinutes: 6,
    timerMode: 'scenario',
    competencies: ['communication', 'service', 'safety'],
    sources: [
      {
        document: 'Ситуации на борту.pdf',
        section: 'с. 11, ситуация 27',
        note: 'Учебная адаптация. Формулировки и баллы требуют методического утверждения.',
      },
    ],
    scene: {
      manifestVersion: 1,
      trainClass: 'comfort',
      spawn: { x: 0, z: 4.45 },
      anchors: [
        {
          id: 'passenger',
          label: 'Пассажир у кресла',
          kind: 'passenger',
          x: -0.5,
          z: 7.11,
          radius: 1.8,
        },
        { id: 'seat', label: 'Загрязнённое место', kind: 'seat', x: -0.5, z: 7.11, radius: 1.8 },
        { id: 'radio', label: 'Служебная связь', kind: 'radio', x: 0, z: 4.4, radius: 1.8 },
      ],
      passenger: {
        name: 'Пассажир А',
        age: 35,
        description: 'Синтетический учебный персонаж; просит помочь с загрязнённым местом.',
        anchorId: 'passenger',
        initialLine: 'Извините, моё место и столик грязные. Помогите, пожалуйста.',
      },
      items: [
        { id: 'dirt-marker', label: 'Маркер загрязнения', anchorId: 'seat', prefab: 'marker' },
      ],
    },
    startNodeId: uuid(101),
    nodes,
    edges,
    childScenarioIds: [],
  },
];
